export const MEMBERS_DATA = [ 
  { firstname: "Zohaib", surname: "Ali", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Orestis", surname: "Angeletos-Paparizos", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Billal", surname: "Arshad", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Jon", surname: "Ayres", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Moira", surname: "Baldiraghi", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Iain", surname: "Baldwin", memberType: "Associate", category: "Dental Technician" }, 
  { firstname: "Tariq", surname: "Bashir", memberType: "Full", category: "Dentist" }, 
  { firstname: "Ole", surname: "Behrens", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Simon", surname: "Belford", memberType: "Full", category: "Dentist" }, 
  { firstname: "John", surname: "Besford", memberType: "Life", category: "Dentist" }, 
  { firstname: "Gurvinder", surname: "Bhirth", memberType: "Full", category: "Dentist" }, 
  { firstname: "Birute", surname: "Bond", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Patrick", surname: "Bottom", memberType: "Life", category: "Dentist" }, 
  { firstname: "Steven", surname: "Campbell", memberType: "Full", category: "Dental Technician" }, 
  { firstname: "Julian", surname: "Caplan", memberType: "Full", category: "Dentist" }, 
  { firstname: "Anmol", surname: "Chander", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Andrew", surname: "Chandrapal", memberType: "Full", category: "Dentist" }, 
  { firstname: "Tomi", surname: "Ciocan", memberType: "Full", category: "Dentist" }, 
  { firstname: "Stuart", surname: "Crook", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Alexandru", surname: "Cucu", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Andrew", surname: "Denny", memberType: "Full", category: "Dentist" }, 
  { firstname: "Rebecca", surname: "Denny", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Nishan", surname: "Dixit", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Ioan", surname: "Dorobantu", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Andrew", surname: "Fennell", memberType: "Full", category: "Dentist" }, 
  { firstname: "Koray", surname: "Feran", memberType: "Full", category: "Dentist" }, 
  { firstname: "Eva", surname: "Forst", memberType: "Full", category: "Dental Technician" }, 
  { firstname: "Yasmin", surname: "George", memberType: "Full", category: "Dentist" }, 
  { firstname: "Massimo", surname: "Giovarruscio", memberType: "Full", category: "Dentist" }, 
  { firstname: "Shane", surname: "Gordon", memberType: "Full", category: "Dentist" }, 
  { firstname: "Marco", surname: "Gresnigt", memberType: "Full", category: "Dentist" }, 
  { firstname: "Alex", surname: "Hadley", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Elaine", surname: "Halley", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Patrick", surname: "Holmes", memberType: "Full", category: "Dentist" }, 
  { firstname: "John", surname: "Hubbard", memberType: "Life", category: "Dental Technician" }, 
  { firstname: "Javed", surname: "Ikram", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Dhanish", surname: "Jabbar", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Gareth", surname: "Jenkins", memberType: "Life", category: "Dentist" }, 
  { firstname: "Stephen", surname: "Jones", memberType: "Life", category: "Dentist" }, 
  { firstname: "Harmit", surname: "Kalsi", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Manraj", surname: "Kalsi", memberType: "Associate", category: "Dentist" }, 
  { firstname: "David", surname: "Kaplan", memberType: "Life", category: "Dentist" }, 
  { firstname: "Des", surname: "Kelly", memberType: "Associate", category: "Dental Technician" }, 
  { firstname: "Imaan", surname: "Khalid", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Fazeela", surname: "Khan-Osborne", memberType: "Full", category: "Dentist" }, 
  { firstname: "Asad", surname: "Lalloo", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Anthony", surname: "Laurie", memberType: "Full", category: "Dental Technician" }, 
  { firstname: "Tidu", surname: "Mankoo", memberType: "Full", category: "Dentist" }, 
  { firstname: "Ljubo", surname: "Marion", memberType: "Life", category: "Dentist" }, 
  { firstname: "Quentin", surname: "McCoach", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Sinead", surname: "McEnhill", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Nikita", surname: "Mehta", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Christian", surname: "Metzner", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Shubham", surname: "Mittal", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Basil", surname: "Mizrahi", memberType: "Full", category: "Dentist" }, 
  { firstname: "Elaine", surname: "Mo", memberType: "Full", category: "Dentist" }, 
  { firstname: "Roy", surname: "Morris", memberType: "Full", category: "Dentist" }, 
  { firstname: "Denise", surname: "Ngsiad", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Hans Kristian", surname: "Ognedal", memberType: "Full", category: "Dentist" }, 
  { firstname: "James", surname: "Ogwang", memberType: "Associate", category: "Dentist" }, 
  { firstname: "Robert", surname: "Oretti", memberType: "Full", category: "Dentist" }, 
  { firstname: "Dipesh", surname: "Parmar", memberType: "Full", category: "Dentist" }, 
  { firstname: "Neilesh", surname: "Paryani", memberType: "Associate", category: "Dentist" },
  { firstname: "Amie", surname: "Patel", memberType: "Associate", category: "Dentist" },
  { firstname: "Amit", surname: "Patel", memberType: "Associate", category: "Dentist" },
  { firstname: "Amit", surname: "Patel", memberType: "Associate", category: "Dentist" },
  { firstname: "Chirag", surname: "Patel", memberType: "Associate", category: "Dentist" },
  { firstname: "Hiral", surname: "Patel", memberType: "Associate", category: "Dentist" },
  { firstname: "Rahul", surname: "Patel", memberType: "Associate", category: "Dentist" },
  { firstname: "Tushar", surname: "Patel", memberType: "Associate", category: "Dentist" },
  { firstname: "Viraj", surname: "Patel", memberType: "Associate", category: "Dentist" },
  { firstname: "André Philip", surname: "Pettemerides", memberType: "Full", category: "Dentist" },
  { firstname: "Ivo", surname: "Raitchev", memberType: "Associate", category: "Dentist" },
  { firstname: "Nadia", surname: "Raitchev", memberType: "Associate", category: "Dentist" },
  { firstname: "Jacqueline", surname: "Rasic", memberType: "Associate", category: "Dentist" },
  { firstname: "Shruti", surname: "Santosh", memberType: "Associate", category: "Dentist" },
  { firstname: "Nigel", surname: "Saynor", memberType: "Full", category: "Dentist" },
  { firstname: "Tristan", surname: "Scott", memberType: "Associate", category: "Dentist" },
  { firstname: "Nik", surname: "Sethi", memberType: "Full", category: "Dentist" },
  { firstname: "Sanjay", surname: "Sethi", memberType: "Full", category: "Dentist" },
  { firstname: "Rajiv", surname: "Sheth", memberType: "Associate", category: "Dentist" },
  { firstname: "Anil", surname: "Shrestha", memberType: "Associate", category: "Dentist" },
  { firstname: "Nik", surname: "Sisodia", memberType: "Full", category: "Dentist" },
  { firstname: "Payman", surname: "Sobhani", memberType: "Full", category: "Dentist" },
  { firstname: "Lara", surname: "Stangacilovic", memberType: "Full", category: "Dentist" },
  { firstname: "Finlay", surname: "Sutton", memberType: "Full", category: "Dentist" },
  { firstname: "Jurgita", surname: "Sybaite", memberType: "Full", category: "Dentist" },
  { firstname: "Mete", surname: "Ucer", memberType: "Associate", category: "Dentist" },
  { firstname: "Devin", surname: "Vaghela", memberType: "Associate", category: "Dentist" },
  { firstname: "Shernaz", surname: "Wadia", memberType: "Associate", category: "Dentist" },
  { firstname: "Martin", surname: "Wanendeya", memberType: "Full", category: "Dentist" },
  { firstname: "David", surname: "Winkler", memberType: "Life", category: "Dentist" },
  { firstname: "Riaz", surname: "Yar", memberType: "Full", category: "Dentist" },
  { firstname: "Nadeem", surname: "Younis", memberType: "Full", category: "Dentist" },
];