import { INavItem, IScientificCard, IWithLink } from "@/types";
import { isRoutable } from "@/types";
export const NAV_ITEMS: INavItem[] = [
  {
    name: "Home",
    link: "/",
  },
  {
    name: "About Us",
    isDropdown: true,
    subItems: [
      {
        name: "About Us",
        link: "/about-us",
        // link: "/",
      },
      {
        name: "Executive Council",
        link: "/executive-council",
      },
      {
        name: "Past Presidents",
        link: "/past-presidents",
      },
      {
        name: "The History of BAAD",
        link: "/the-history-of-baad",
      },
      {
        name: "Lambert Fick Memorial",
        link: "/lambert-fick-memorial",
      },
      {
        name: "Revised Constitution 2024",
        link: "/revised-constitution.pdf",
      },
      {
        name: "Testimonials",
        link: "/testimonials",
      },
    ],
  },
  {
    name: "Membership",
    isDropdown: true,
    subItems: [
      {
        name: "Membership",
        link: "/membership",
      },
      {
        name: "Members",
        link: "/members",
      },
      {
        name: "Becoming a Full Member",
        link: "/full-member",
      },
      {
        name: "Associate Membership",
        link: "/associate-membership",
      },
    ],
  },
  {
    name: "Scientific Conferences",
    link: "/scientific-conferences",
  },
  {
    name: "Masterclasses",
    link: "/masterclasses",
    // link: "/",
  },
  {
    name: "Contact us",
    link: "/contact-us",
  },
  {
    name: "Book Now",
    link: "/book-now",
  },
];

export const WELCOME_TO = {
  heading:
    "Welcome to <span id='heading-two-span'>British Academy of Aesthetic</span> Dentistry",
  upperPara: "Advancing the Art & Science of Dentistry",
  data: [
    {
      image: "/our-mission.webp",
      heading: "Our",
      headingTwo: "Mission",
      para: "Promoting excellence in aesthetic dentistry across the UK through education, innovation, and the sharing of expertise between clinicians, technicians, and academics.",
      btn: "About BAAD",
      href: "/",
    },
    {
      // image: "/our-leadership.webp",
      image: "/leadership-two.png",
      heading: "Our ",
      headingTwo: "Leadership",
      para: "Meet the esteemed professionals driving BAAD’s vision forward—uniting multidisciplinary perspectives to shape the future of aesthetic dentistry.",
      reverse: true,
      href: "/",
      btn: "Get to Know Us",
    },
    {
      image: "/our-community.jpg",
      heading: "Our",
      headingTwo: "Community",
      para: "Join a dynamic network of members committed to clinical excellence, continuous learning, and elevating standards in aesthetic and restorative dental care.",
      href: "/",
      btn: "Start Your Journey",
    },
  ],
};
export const MASTER_CLASSES = [
  {
    image: "/BAAD-Masterclass-Enter-The-Matrix-1086x1536.png",
    year: "2023",
    description: "Friday 16th June 2023 – ‘Enter The Matrix’ – A Masterclass",
  },
  {
    image: "/baad-masterclass-mission-impossible-pdf.jpg",
    year: "2022",
    description:
      "Friday 20th May 2022 – ‘Restorative Mission Impossible’ – The Compleat Angler, Marlow",
    link: "/baad-masterclass-mission-impossible.pdf",
  },
  {
    image: "/Untitled-design-1.png",
    year: "2020",
    description: "Friday 1st May 2020",
    link: "/Untitled-design-1.png",
  },
  {
    image: "/Untitled-design-724x1024.png",
    year: "2019",
    description: "Friday 15th November 2019",
    link: "/Untitled-design-724x1024.png",
  },
  {
    image: "/BAAD-E2019-pdf.jpg",
    year: "2019",
    description: "Friday 28th June 2019",
    link: "/BAAD-E2019-pdf.jpg",
  },
  {
    image: "/BAAD-L2018-pdf.jpg",
    year: "2018",
    description: "Friday 14th September 2018",
    link: "/BAAD-L2018-pdf.jpg",
  },
  {
    image: "/BAAD-E2018-pdf.jpg",
    year: "2018",
    description: "Friday 16th March 2018",
    link: "/BAAD-E2018-pdf.jpg",
  },
  {
    image: "/BAAD-L2017-pdf.jpg",
    year: "2017",
    description: "Friday 16th March 2018",
    link: "/BAAD-L2017-pdf.jpg",
  },
  {
    image: "/BAAD-E2017-pdf.jpg",
    year: "2017",
    description: "Friday 31st March 2017",
    link: "/BAAD-E2017-pdf.jpg",
  },
  {
    image: "/BAAD-L2016-pdf.jpg",
    year: "2016",
    description: "Friday 18th November 2016",
    link: "/BAAD-L2016-pdf.jpg",
  },
  {
    image: "/BAAD-M2016-pdf.jpg",
    year: "2016",
    description: "Friday 16th September 2016",
    link: "/BAAD-M2016-pdf.jpg",
  },
  {
    image: "/BAAD-E2016-pdf.jpg",
    year: "2016",
    description: "Friday 15th April 2016",
    link: "/BAAD-E2016-pdf.jpg",
  },
  {
    image: "/BAAD-E2016-pdf.jpg",
    year: "2016",
    description: "Friday 20th November 2015",
    link: "/BAAD-E2016-pdf.jpg",
  },
  {
    image: "/BAAD-L2015-pdf.jpg",
    year: "2015",
    description: "Friday 20th November 2015",
    link: "/BAAD-L2015-pdf.jpg",
  },
  {
    image: "/BAAD-M2015-pdf.jpg",
    year: "2015",
    description: "Friday 11th September 2015",
    link: "/BAAD-M2015-pdf.jpg",
  },
  {
    image: "/BAAD-E2015-724x1024.png",
    year: "2015",
    description: "Friday 24th April 2015",
    link: "/BAAD-E2015-724x1024.png",
  },
  {
    image: "/BAAD-L2014-pdf.jpg",
    year: "2014",
    description: "Friday 21st November 2014",
    link: "/BAAD-L2014-pdf.jpg",
  },
  {
    image: "/BAAD-E2014-pdf.jpg",
    year: "2014",
    description: "Friday 12th September 2014",
    link: "/BAAD-E2014-pdf.jpg",
  },
];
export const SCIENTIFIC_CARDS: IScientificCard[] = [
  {
    description: "2025 – Super Hero's",
    pageHeader: "Super Hero’s: With great power comes great responsibility",
    heading: "AESTHETIC WIZARDRY: UNLOCKING THE CHAMBER OF SECRETS",
    venue: "The Hilton Syon Park, Park Road, Islesworth, TW8 8JF",
    date: "Friday 24th & Saturday 25th January 2025",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Prof. MArleen Peumans",
      "Dr. Giulio Pavolucci",
      "mr.Stefan Roozen",
      "Dr.Benjamin Cortasse",
      "Dr.Mirela Feraru",
      "Dr. Lara Stangacilovic",
      "Dr. Roberto Perasso",
      "Dr.Monica Imelio",
      "Dr.Daniel Flynn",
      "Dr. Paulo Carvalho",
      "Dr.Didier Dietschi",
    ],
    image: "/baad-super-hero.png",
    learnMoreLink: "/",
    programmeLink: "/",
    link: "super-heros-with-great-power-comes-great-responsibility",
  },
  {
    image: "/bAAD-2024-Conference-Flyer.jpg",
    description: "2024 – Scientific Meeting",
    pageHeader: "Aesthetic Wizardry:  Unlocking The Chamber Of Secrets",
    heading: "AESTHETIC WIZARDRY: UNLOCKING THE CHAMBER OF SECRETS",
    venue: "Great Fosters Hotel, Surrey, TW20 9UR",
    date: "Friday 26th & Saturday 27th January 2024",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Lorenzo Breschi",
      "Ronaldo Hirata",
      "Jason Smithson",
      "Snjezana Pohl",
      "Mark Ludlow",
      "Javier Tapia Guadix",
      "Ernest Lucas-Taule",
      "Giuseppe Romeo",
      "David De Franco",
      "Dr Stefano Gracis",
    ],
    link: "aesthetic-wizardry-unlocking-the-chamber-of-secrets",
    imageArray: [
      "aesthetic-wizardry/1.jpg",
      "aesthetic-wizardry/2.jpg",
      "aesthetic-wizardry/3.jpg",
      "aesthetic-wizardry/4.jpg",
      "aesthetic-wizardry/5.jpg",
      "aesthetic-wizardry/6.jpg",
      "aesthetic-wizardry/7.jpg",
      "aesthetic-wizardry/8.gif",
      "aesthetic-wizardry/9.gif",
      "aesthetic-wizardry/10.jpg",
      "aesthetic-wizardry/11.jpg",
      "aesthetic-wizardry/12.jpg",
      "aesthetic-wizardry/13.jpg",
      "aesthetic-wizardry/14.jpg",
      "aesthetic-wizardry/15.jpg",
      "aesthetic-wizardry/16.jpg",
      "aesthetic-wizardry/17.jpg",
      "aesthetic-wizardry/18.gif",
      "aesthetic-wizardry/19.gif",
      "aesthetic-wizardry/20.jpg",
      "aesthetic-wizardry/21.jpg",
      "aesthetic-wizardry/22.jpg",
      "aesthetic-wizardry/23.jpg",
      "aesthetic-wizardry/24.jpg",
      "aesthetic-wizardry/25.jpg",
      "aesthetic-wizardry/26.jpg",
      "aesthetic-wizardry/27.jpg",
      "aesthetic-wizardry/28.gif",
      "aesthetic-wizardry/29.gif",
      "aesthetic-wizardry/30.jpg",
      "aesthetic-wizardry/31.jpg",
      "aesthetic-wizardry/32.jpg",
      "aesthetic-wizardry/33.jpg",
      "aesthetic-wizardry/34.jpg",
      "aesthetic-wizardry/35.jpg",
      "aesthetic-wizardry/36.jpg",
      "aesthetic-wizardry/37.jpg",
      "aesthetic-wizardry/38.gif",
      "aesthetic-wizardry/39.gif",
      "aesthetic-wizardry/40.jpg",
      "aesthetic-wizardry/41.jpg",
      "aesthetic-wizardry/42.jpg",
      "aesthetic-wizardry/43.jpg",
      "aesthetic-wizardry/44.jpg",
      "aesthetic-wizardry/45.jpg",
      "aesthetic-wizardry/46.jpg",
      "aesthetic-wizardry/47.jpg",
      "aesthetic-wizardry/48.gif",
      "aesthetic-wizardry/49.gif",
      "aesthetic-wizardry/50.jpg",
      "aesthetic-wizardry/51.jpg",
      "aesthetic-wizardry/52.jpg",
      "aesthetic-wizardry/53.jpg",
      "aesthetic-wizardry/54.jpg",
      "aesthetic-wizardry/55.jpg",
      "aesthetic-wizardry/56.jpg",
      "aesthetic-wizardry/57.jpg",
      "aesthetic-wizardry/58.gif",
      "aesthetic-wizardry/59.gif",
      "aesthetic-wizardry/60.jpg",
      "aesthetic-wizardry/61.jpg",
      "aesthetic-wizardry/62.jpg",
      "aesthetic-wizardry/63.jpg",
      "aesthetic-wizardry/64.jpg",
      "aesthetic-wizardry/65.jpg",
      "aesthetic-wizardry/66.jpg",
      "aesthetic-wizardry/67.jpg",
      "aesthetic-wizardry/68.gif",
      "aesthetic-wizardry/69.gif",
      "aesthetic-wizardry/70.jpg",
      "aesthetic-wizardry/71.jpg",
      "aesthetic-wizardry/72.jpg",
      "aesthetic-wizardry/73.jpg",
      "aesthetic-wizardry/74.jpg",
      "aesthetic-wizardry/75.jpg",
      "aesthetic-wizardry/76.jpg",
      "aesthetic-wizardry/77.jpg",
      "aesthetic-wizardry/78.jpg",
      "aesthetic-wizardry/79.jpg",
      "aesthetic-wizardry/80.jpg",
      "aesthetic-wizardry/81.jpg",
      "aesthetic-wizardry/82.jpg",
      "aesthetic-wizardry/83.jpg",
      "aesthetic-wizardry/84.jpg",
      "aesthetic-wizardry/85.jpg",
      "aesthetic-wizardry/86.gif",
      "aesthetic-wizardry/87.gif",
      "aesthetic-wizardry/88.jpg",
      "aesthetic-wizardry/89.jpg",
      "aesthetic-wizardry/90.jpg",
      "aesthetic-wizardry/91.jpg",
      "aesthetic-wizardry/92.jpg",
      "aesthetic-wizardry/93.jpg",
      "aesthetic-wizardry/94.jpg",
      "aesthetic-wizardry/95.jpg",
      "aesthetic-wizardry/96.gif",
      "aesthetic-wizardry/97.gif",
      "aesthetic-wizardry/98.jpg",
      "aesthetic-wizardry/99.jpg",
      "aesthetic-wizardry/100.jpg",
      "aesthetic-wizardry/101.jpg",
      "aesthetic-wizardry/102.jpg",
      "aesthetic-wizardry/103.jpg",
      "aesthetic-wizardry/104.jpg",
      "aesthetic-wizardry/105.jpg",
      "aesthetic-wizardry/106.gif",
      "aesthetic-wizardry/107.gif",
      "aesthetic-wizardry/108.jpg",
      "aesthetic-wizardry/109.jpg",
      "aesthetic-wizardry/110.jpg",
      "aesthetic-wizardry/111.jpg",
      "aesthetic-wizardry/112.jpg",
      "aesthetic-wizardry/113.jpg",
      "aesthetic-wizardry/114.jpg",
      "aesthetic-wizardry/115.jpg",
      "aesthetic-wizardry/116.gif",
      "aesthetic-wizardry/117.gif",
      "aesthetic-wizardry/118.jpg",
      "aesthetic-wizardry/119.jpg",
      "aesthetic-wizardry/120.jpg",
      "aesthetic-wizardry/121.jpg",
      "aesthetic-wizardry/122.jpg",
      "aesthetic-wizardry/123.jpg",
      "aesthetic-wizardry/124.jpg",
      "aesthetic-wizardry/125.jpg",
      "aesthetic-wizardry/126.gif",
      "aesthetic-wizardry/127.gif",
      "aesthetic-wizardry/128.jpg",
      "aesthetic-wizardry/129.jpg",
      "aesthetic-wizardry/130.jpg",
      "aesthetic-wizardry/131.jpg",
      "aesthetic-wizardry/132.jpg",
      "aesthetic-wizardry/133.jpg",
      "aesthetic-wizardry/134.jpg",
      "aesthetic-wizardry/135.jpg",
      "aesthetic-wizardry/136.gif",
      "aesthetic-wizardry/137.gif",
      "aesthetic-wizardry/138.jpg",
      "aesthetic-wizardry/139.jpg",
      "aesthetic-wizardry/140.jpg",
      "aesthetic-wizardry/141.jpg",
      "aesthetic-wizardry/142.jpg",
      "aesthetic-wizardry/143.jpg",
      "aesthetic-wizardry/144.jpg",
      "aesthetic-wizardry/145.jpg",
      "aesthetic-wizardry/146.gif",
      "aesthetic-wizardry/147.gif",
      "aesthetic-wizardry/148.jpg",
      "aesthetic-wizardry/149.jpg",
      "aesthetic-wizardry/150.jpg",
      "aesthetic-wizardry/151.jpg",
      "aesthetic-wizardry/152.jpg",
      "aesthetic-wizardry/153.jpg",
      "aesthetic-wizardry/154.jpg",
      "aesthetic-wizardry/155.jpg",
      "aesthetic-wizardry/156.gif",
      "aesthetic-wizardry/157.gif",
      "aesthetic-wizardry/158.jpg",
      "aesthetic-wizardry/159.jpg",
      "aesthetic-wizardry/160.jpg",
      "aesthetic-wizardry/161.jpg",
      "aesthetic-wizardry/162.jpg",
      "aesthetic-wizardry/163.jpg",
      "aesthetic-wizardry/164.jpg",
      "aesthetic-wizardry/165.jpg",
      "aesthetic-wizardry/166.gif",
      "aesthetic-wizardry/167.gif",
      "aesthetic-wizardry/168.jpg",
      "aesthetic-wizardry/169.jpg",
      "aesthetic-wizardry/170.jpg",
      "aesthetic-wizardry/171.jpg",
      "aesthetic-wizardry/172.jpg",
      "aesthetic-wizardry/173.jpg",
      "aesthetic-wizardry/174.jpg",
      "aesthetic-wizardry/175.jpg",
      "aesthetic-wizardry/176.gif",
      "aesthetic-wizardry/177.gif",
      "aesthetic-wizardry/178.jpg",
      "aesthetic-wizardry/179.jpg",
      "aesthetic-wizardry/180.jpg",
      "aesthetic-wizardry/181.jpg",
      "aesthetic-wizardry/182.jpg",
      "aesthetic-wizardry/183.jpg",
      "aesthetic-wizardry/184.jpg",
      "aesthetic-wizardry/185.jpg",
      "aesthetic-wizardry/186.gif",
      "aesthetic-wizardry/187.gif",
      "aesthetic-wizardry/188.jpg",
      "aesthetic-wizardry/189.jpg",
      "aesthetic-wizardry/190.jpg",
      "aesthetic-wizardry/191.jpg",
      "aesthetic-wizardry/192.jpg",
      "aesthetic-wizardry/193.jpg",
      "aesthetic-wizardry/194.jpg",
      "aesthetic-wizardry/195.jpg",
      "aesthetic-wizardry/196.gif",
      "aesthetic-wizardry/197.gif",
      "aesthetic-wizardry/198.jpg",
      "aesthetic-wizardry/199.jpg",
      "aesthetic-wizardry/200.jpg",
      "aesthetic-wizardry/201.jpg",
      "aesthetic-wizardry/202.jpg",
      "aesthetic-wizardry/203.jpg",
      "aesthetic-wizardry/204.jpg",
      "aesthetic-wizardry/205.jpg",
      "aesthetic-wizardry/206.gif",
      "aesthetic-wizardry/207.gif",
      "aesthetic-wizardry/208.jpg",
      "aesthetic-wizardry/209.jpg",
      "aesthetic-wizardry/210.jpg",
      "aesthetic-wizardry/211.jpg",
      "aesthetic-wizardry/212.jpg",
      "aesthetic-wizardry/213.jpg",
      "aesthetic-wizardry/214.jpg",
      "aesthetic-wizardry/215.jpg",
      "aesthetic-wizardry/216.gif",
      "aesthetic-wizardry/217.gif",
      "aesthetic-wizardry/218.jpg",
      "aesthetic-wizardry/219.jpg",
      "aesthetic-wizardry/220.jpg",
      "aesthetic-wizardry/221.jpg",
      "aesthetic-wizardry/222.jpg",
      "aesthetic-wizardry/223.jpg",
      "aesthetic-wizardry/224.jpg",
      "aesthetic-wizardry/225.jpg",
      "aesthetic-wizardry/226.gif",
      "aesthetic-wizardry/227.gif",
      "aesthetic-wizardry/228.jpg",
      "aesthetic-wizardry/229.jpg",
      "aesthetic-wizardry/230.jpg",
      "aesthetic-wizardry/231.jpg",
      "aesthetic-wizardry/232.jpg",
      "aesthetic-wizardry/233.jpg",
      "aesthetic-wizardry/234.jpg",
      "aesthetic-wizardry/235.jpg",
      "aesthetic-wizardry/236.gif",
      "aesthetic-wizardry/237.gif",
      "aesthetic-wizardry/238.jpg",
      "aesthetic-wizardry/239.jpg",
      "aesthetic-wizardry/240.jpg",
      "aesthetic-wizardry/241.jpg",
      "aesthetic-wizardry/242.jpg",
      "aesthetic-wizardry/243.jpg",
      "aesthetic-wizardry/244.jpg",
      "aesthetic-wizardry/245.jpg",
      "aesthetic-wizardry/246.gif",
      "aesthetic-wizardry/247.gif",
      "aesthetic-wizardry/248.jpg",
      "aesthetic-wizardry/249.jpg",
      "aesthetic-wizardry/250.jpg",
      "aesthetic-wizardry/251.jpg",
      "aesthetic-wizardry/252.jpg",
      "aesthetic-wizardry/253.jpg",
      "aesthetic-wizardry/254.jpg",
      "aesthetic-wizardry/255.jpg",
      "aesthetic-wizardry/256.gif",
      "aesthetic-wizardry/257.gif",
      "aesthetic-wizardry/258.jpg",
      "aesthetic-wizardry/259.jpg",
      "aesthetic-wizardry/260.jpg",
      "aesthetic-wizardry/261.jpg",
      "aesthetic-wizardry/262.jpg",
      "aesthetic-wizardry/263.jpg",
      "aesthetic-wizardry/264.jpg",
      "aesthetic-wizardry/265.jpg",
      "aesthetic-wizardry/266.gif",
      "aesthetic-wizardry/267.gif",
      "aesthetic-wizardry/268.jpg",
      "aesthetic-wizardry/269.jpg",
      "aesthetic-wizardry/270.jpg",
      "aesthetic-wizardry/271.jpg",
      "aesthetic-wizardry/272.jpg",
      "aesthetic-wizardry/273.jpg",
      "aesthetic-wizardry/274.jpg",
      "aesthetic-wizardry/275.jpg",
      "aesthetic-wizardry/276.gif",
      "aesthetic-wizardry/277.gif",
      "aesthetic-wizardry/278.jpg",
      "aesthetic-wizardry/279.jpg",
      "aesthetic-wizardry/280.jpg",
      "aesthetic-wizardry/281.jpg",
      "aesthetic-wizardry/282.jpg",
      "aesthetic-wizardry/283.jpg",
      "aesthetic-wizardry/284.jpg",
      "aesthetic-wizardry/285.jpg",
      "aesthetic-wizardry/286.gif",
      "aesthetic-wizardry/287.gif",
      "aesthetic-wizardry/288.jpg",
      "aesthetic-wizardry/289.jpg",
      "aesthetic-wizardry/290.jpg",
      "aesthetic-wizardry/291.jpg",
      "aesthetic-wizardry/292.jpg",
      "aesthetic-wizardry/293.jpg",
      "aesthetic-wizardry/294.gif",
      "aesthetic-wizardry/295.gif",
      "aesthetic-wizardry/296.jpg",
      "aesthetic-wizardry/297.jpg",
      "aesthetic-wizardry/298.jpg",
      "aesthetic-wizardry/299.jpg",
      "aesthetic-wizardry/300.jpg",
      "aesthetic-wizardry/301.jpg",
      "aesthetic-wizardry/302.jpg",
      "aesthetic-wizardry/303.jpg",
      "aesthetic-wizardry/304.gif",
      "aesthetic-wizardry/305.gif",
      "aesthetic-wizardry/306.jpg",
      "aesthetic-wizardry/307.jpg",
      "aesthetic-wizardry/308.jpg",
      "aesthetic-wizardry/309.jpg",
      "aesthetic-wizardry/310.jpg",
      "aesthetic-wizardry/311.jpg",
      "aesthetic-wizardry/312.jpg",
      "aesthetic-wizardry/313.jpg",
      "aesthetic-wizardry/314.gif",
      "aesthetic-wizardry/315.gif",
      "aesthetic-wizardry/316.jpg",
      "aesthetic-wizardry/317.jpg",
      "aesthetic-wizardry/318.jpg",
      "aesthetic-wizardry/319.jpg",
      "aesthetic-wizardry/320.jpg",
      "aesthetic-wizardry/321.jpg",
      "aesthetic-wizardry/322.jpg",
      "aesthetic-wizardry/323.jpg",
      "aesthetic-wizardry/324.gif",
      "aesthetic-wizardry/325.gif",
      "aesthetic-wizardry/326.jpg",
      "aesthetic-wizardry/327.jpg",
      "aesthetic-wizardry/328.jpg",
      "aesthetic-wizardry/329.jpg",
      "aesthetic-wizardry/330.jpg",
      "aesthetic-wizardry/331.jpg",
      "aesthetic-wizardry/332.jpg",
      "aesthetic-wizardry/333.jpg",
      "aesthetic-wizardry/334.gif",
      "aesthetic-wizardry/335.gif",
      "aesthetic-wizardry/336.jpg",
      "aesthetic-wizardry/337.jpg",
      "aesthetic-wizardry/338.jpg",
      "aesthetic-wizardry/339.jpg",
      "aesthetic-wizardry/340.jpg",
      "aesthetic-wizardry/341.jpg",
      "aesthetic-wizardry/342.jpg",
      "aesthetic-wizardry/343.jpg",
      "aesthetic-wizardry/344.gif",
      "aesthetic-wizardry/345.gif",
      "aesthetic-wizardry/346.jpg",
      "aesthetic-wizardry/347.jpg",
      "aesthetic-wizardry/348.jpg",
      "aesthetic-wizardry/349.jpg",
      "aesthetic-wizardry/350.jpg",
      "aesthetic-wizardry/351.jpg",
      "aesthetic-wizardry/352.jpg",
      "aesthetic-wizardry/353.jpg",
      "aesthetic-wizardry/354.gif",
      "aesthetic-wizardry/355.gif",
      "aesthetic-wizardry/356.jpg",
      "aesthetic-wizardry/357.jpg",
      "aesthetic-wizardry/358.jpg",
      "aesthetic-wizardry/359.jpg",
      "aesthetic-wizardry/360.jpg",
      "aesthetic-wizardry/361.jpg",
      "aesthetic-wizardry/362.jpg",
      "aesthetic-wizardry/363.jpg",
      "aesthetic-wizardry/364.gif",
      "aesthetic-wizardry/365.gif",
      "aesthetic-wizardry/366.jpg",
      "aesthetic-wizardry/367.jpg",
      "aesthetic-wizardry/368.jpg",
      "aesthetic-wizardry/369.jpg",
      "aesthetic-wizardry/370.jpg",
      "aesthetic-wizardry/371.jpg",
      "aesthetic-wizardry/372.jpg",
      "aesthetic-wizardry/373.jpg",
      "aesthetic-wizardry/374.gif",
      "aesthetic-wizardry/375.gif",
      "aesthetic-wizardry/376.jpg",
      "aesthetic-wizardry/377.jpg",
      "aesthetic-wizardry/378.jpg",
      "aesthetic-wizardry/379.jpg",
      "aesthetic-wizardry/380.jpg",
      "aesthetic-wizardry/381.jpg",
      "aesthetic-wizardry/382.jpg",
      "aesthetic-wizardry/383.jpg",
      "aesthetic-wizardry/384.gif",
      "aesthetic-wizardry/385.gif",
      "aesthetic-wizardry/386.jpg",
      "aesthetic-wizardry/387.jpg",
      "aesthetic-wizardry/388.jpg",
      "aesthetic-wizardry/389.jpg",
      "aesthetic-wizardry/390.jpg",
      "aesthetic-wizardry/391.jpg",
      "aesthetic-wizardry/392.jpg",
      "aesthetic-wizardry/393.jpg",
      "aesthetic-wizardry/394.gif",
      "aesthetic-wizardry/395.gif",
      "aesthetic-wizardry/396.jpg",
      "aesthetic-wizardry/397.jpg",
      "aesthetic-wizardry/398.jpg",
      "aesthetic-wizardry/399.jpg",
      "aesthetic-wizardry/400.jpg",
      "aesthetic-wizardry/401.jpg",
      "aesthetic-wizardry/402.jpg",
      "aesthetic-wizardry/403.jpg",
      "aesthetic-wizardry/404.gif",
      "aesthetic-wizardry/405.gif",
      "aesthetic-wizardry/406.jpg",
      "aesthetic-wizardry/407.jpg",
      "aesthetic-wizardry/408.jpg",
      "aesthetic-wizardry/409.jpg",
      "aesthetic-wizardry/410.jpg",
      "aesthetic-wizardry/411.jpg",
      "aesthetic-wizardry/412.jpg",
      "aesthetic-wizardry/413.jpg",
      "aesthetic-wizardry/414.gif",
      "aesthetic-wizardry/415.gif",
      "aesthetic-wizardry/416.jpg",
      "aesthetic-wizardry/417.jpg",
      "aesthetic-wizardry/418.jpg",
      "aesthetic-wizardry/419.jpg",
      "aesthetic-wizardry/420.jpg",
      "aesthetic-wizardry/421.jpg",
      "aesthetic-wizardry/422.jpg",
      "aesthetic-wizardry/423.jpg",
      "aesthetic-wizardry/424.gif",
      "aesthetic-wizardry/425.gif",
      "aesthetic-wizardry/426.jpg",
    ],
  },
  {
    image: "/bAAD-Conference-2023.png",
    description: "2023 – Scientific Meeting",
    pageHeader: "‘A’esthetic Fusion: Gnathology with a Touch of Spice",
    heading: "‘A’esthetic Fusion: Gnathology with a Touch of Spice",
    venue: "Great Fosters Hotel, Surrey, TW20 9UR",
    date: "Friday 27th & Saturday 28th January 2023",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Gianfranco Politano (IT)",
      "Bart Van Meerbeek (BE)",
      "Leonardo Bacherini (IT)",
      "Martin Wanendeya (UK)",
      "Daniele Cardaropoli (IT)",
      "Bjorn Ludwig (DE)",
      "Przemek Seweryniak (SE)",
      "Florian Beuer (DE)",
      "Marco Gresnigt (NL)",
    ],
    link: "aesthetic-fusion-gnathology-with-a-touch-of-spice",
  },
  {
    image: "/baad-2022-front.png",
    description: "2022 – Scientific Meeting",
    pageHeader: "The Wonderful World of BAAD Scientific Meeting 2022",
    heading: "The Wonderful World of BAAD",
    venue: "Ashdown Park Hotel",
    date: "Friday 28th & Saturday 29th January 2022",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Andrew Chandrapal – United Kingdom",
      "Sanjay Sethi – United Kingdom",
      "Dipesh Pramar – United Kingdom",
      "Daniele Cardaropoli – Italy",
      "Tomas Linkevicius – Lithuania",
      "Roxana Petcu – Romania",
      "Lukasz Lassmann – Poland",
      "Antonello Appiani – Italy",
      "Danielle Rodoni – Italy",
      "Tidu Mankoo – United Kingdom",
    ],
    link: "british-academy-of-aesthetic-dentistry-2022-annual-conference",
  },
  {
    image: "/bAAD-2020-768x223.jpeg",
    description: "2020 – Scientific Meeting",
    pageHeader: "Crystal Clear Dentistry Scientific Meeting 2020",
    heading: "Crystal Clear Dentistry",
    venue: "Stoke Park Club, Buckinghamshire",
    date: "Friday 24th & Saturday 25th January 2020",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Roberto Turrini",
      "Martina Stefanini",
      "Jose Carlos Martins da Rosa",
      "Guido Fichera",
      "Peter Pizzi",
      "Joana Garcez",
      "Stefano Conti",
      "Pier Carlo Frabboni",
      "Franck Bonnet",
      "Sandro Cortellini",
    ],
    link: "crystal-clear-dentistry-scientific-meeting-2020",
  },
  {
    image: "/BAAD-2019-768x223.jpeg",
    description: "2019 – Scientific Meeting",
    link: "dentistry-beyond-pure-imagination-scientific-meeting-2019",
    pageHeader: "Stoke Park Club, Buckinghamshire",
    heading: "Dentistry Beyond Pure Imagination",
    venue: "Stoke Park Club, Buckinghamshire",
    date: "Friday 25th & Saturday 26th January 2019",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Domenico Massironi – Italy",
      "Carlo Ghezzi – Italy",
      "Alessandro Conti – Italy",
      "Miltiadis Mitsias – Greece",
      "Ricardo Kern – Brazil",
      "Jurgen Mehrhof – Germany",
      "Tony Rotondo – Australia",
      "Marco Veneziani – Italy",
      "Matthias Kern – Germany",
      "Francesca Vailati – Switzerland",
      "Renato Cocconi – Italy",
      "Niko Perakis – Italy",
    ],
  },
  {
    image: "/BAAD-2018-768x220.jpeg",
    description: "2018 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-scientific-meeting-2018",
    pageHeader: "Unlocking the secrets of excellence Scientific Meeting 2018",
    heading: "Unlocking the secrets of excellence",
    venue: "Stoke Park Club, Park Road, Stoke Poges, Buckinghamshire",
    date: "26th-27th January 2018",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Jordi Manuata – Mexico",
      "Marko Jakovac – Croatia",
      "Oded Bahat – USA",
      "Ion Zabalegui – Spain",
      "Wael Att – Germany",
      "Riccardo Becciani – Italy",
      "Stefano Inglese – Italy",
      "Olivier Carcuac – Sweden",
      "Finlay Sutton – UK",
      "Nitzan Bichacho – Israel",
      "Mirela Feraru – Israel",
    ],
  },
  {
    image: "/BAAD-2017-768x223.jpeg",
    description: "2017 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-scientific-meeting-2017",
    pageHeader:
      "British Academy of Aesthetic Dentistry Scientific Meeting 2017",
    heading: "New Horizons... Fact or Fiction",
    venue: "Stoke Park Club, Buckinghamshire",
    date: "Friday 27th & Saturday 28th January 2017",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Otto Zuhr – Germany",
      "Ronald Jung – Switzerland",
      "David Klaff – United Kingdom",
      "Luiz Narciso Baratieri – Brazil",
      "Lawrence Brecht – America",
      "Branko Bojovic – America",
      "Josep Oliva – Spain",
      "Pawel Plakwicz – Poland",
      "Francesco Mintrone – Italy",
      "Nasser Shaderman – Malaysia",
    ],
  },
  {
    image: "/BAAD-Early-2016-768x223.jpeg",
    description: "2016 – Gala Dinner",
    link: "british-academy-of-aesthetic-dentistry-2016-gala-dinner",
    pageHeader: "Dentistry Beyond Pure Imagination Gala Dinner 2016",
    heading: "Forward Thinking - Powerful Hindsight",
    venue: "Stoke Park Club, Park Road, Stoke Poges, Buckinghamshire",
    date: "29th-30th January 2016",
    upperPara: "Below are the speakers for this meeting:",
    speakersDateBased: [
      {
        date: "Friday 29th January",
        speak: [
          "Ivo Krejci (Switzerland)",
          "Angelo Putignano (Italy)",
          "Daniel Edelhoff (Germany)",
          "Markus Blatz (U.S.A.)",
        ],
      },
      {
        date: "Saturday 30th January",
        speak: [
          "Massimo Simion (Italy)",
          "Paulo Malo (Portugal)",
          "Giulio Rasperini (Italy)",
          "Inaki Gamborena (Spain)",
          "Nondas Vlachopoulos (Greece)",
        ],
      },
    ],
  },
  {
    image: "/BAAD-Early-2016-768x223.jpeg",
    description: "2016 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2016-annual-conference",
    pageHeader: "Forward Thinking - Powerful Hndsight 2016 Annual Conference",
    heading: "Foward Thinking - Powerful Hindsight",
    venue: "Stoke Park Club, Buckinghamshire",
    date: "29th-30th January 2016",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Ivo Krejci – Switzerland",
      "Angelo Putignano – Italy",
      "Daniel Edelhoff – Germany",
      "Markus Blatz  – U.S.A.",
    ],
  },
  {
    image: "/BAAD-2015.jpeg",
    description: "2015 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2015-annual-conference",
    pageHeader: "Inspire to Aspire Scientific Meeting 2015",
    heading: "Inspire to Aspire Scientific Meeting 2015",
    venue: "Stoke Park Club, Buckinghamshire",
    date: "30th – 31st January 2015",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Walter Devoto – Italy",
      "Mauro Fradeani – Italy",
      "Oliver Brix – Germany",
      "Daniel Thoma – Switzerland",
      "Giovanni Bruschi – Italy",
      "Mario Semenza – Italy",
      "Irena Sailer – Switzerland",
      "Alessandro Devigus – Switzerland",
      "Giovanni Zucchelli – Italy",
    ],
  },
  {
    image: "/BAAD-2014.jpeg",
    description: "2014 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2014-annual-conference",
    pageHeader: "Annual Scientific Meeting 2014",
    heading: "Annual Scientific Meeting 2014",
    venue: "Stoke Park Club, Buckinghamshire",
    date: "24th – 25th January 2014",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Marco Cossu – Switzerland",
      "Nikos Donos – United Kingdom",
      "Didier Fillion – France",
      "Stefano Gracis – Italy",
      "Bernd Giesenhagen – Germany",
      "Biju Krishnan – United Kingdom",
      "Tif Qureshi – United Kingdom",
      "Rafi Romano – Israel",
      "Giulio Rasperini – Italy",
      "Istvan Urban – Hungary",
      "Anthony Viazis – U.S.A.",
    ],
  },
  {
    image: "/4-724x1024.png",
    description: "2013 – Scientific Meeting",
    // link: "/",
  },
  {
    image: "/BAAD-2012.jpeg",
    description: "2012 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2012-annual-conference",
    pageHeader:
      "Aesthetic Choices - Point and Counterpoint Scientific Meeting 2012",
    heading: "Aesthetic Choices - Point & Counterpoint",
    venue: "Stoke Park Club, Buckinghamshire",
    date: "2012",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Terry Green – U.S.A.",
      "Piet Haers – United Kingdom",
      "Carlo Marinello – Switzerland",
      "Basil Mizrahi – United Kingdom",
      "Dan Nathanson – U.S.A.",
      "Andrea Ricci – Italy",
      "Giano Ricci – Italy",
      "Giuseppe Romeo – Italy",
      "Jeff Rouse – U.S.A.",
    ],
  },
  {
    image: "/6-724x1024.png",
    description: "2011 – Scientific Meeting",
    // link: "/",
  },
  {
    image: "/BAAD-2010.jpeg",
    description: "2010 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2010-annual-conference",
    pageHeader:
      "Science Guides But our Hands do the Walking Scientific Meeting 2010",
    heading: "Science Guides but or hands do the walking",
    venue: "Beaumont House",
    date: "25th – 26th June 2010",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Angelo Putignano – Italy",
      "Ulf Krueger-Janson – Germany",
      "Tidu Mankoo – United Kingdom",
    ],
  },
  {
    image: "/7-724x1024.png",
    description: "2009 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2009-annual-conference",
    pageHeader: "Team Aesthetics Scientific Meeting 2009",
    heading: "Team Aesthetics",
    venue:
      "The Vale Hotel, Gold & Spa Resort, Hensol Park, Nr.Cardiff Vale of Glamorgan",
    date: "10th, 11th, & 12th September",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Prof Ian Needleman",
      "Dr Michael Sultan",
      "Dr Sven Rinke",
      "Mr Carsten Fischer",
      "Dr Tif Qureshi",
      "Dr James Goolnik",
      "Dr Basil Mizrahi",
      "Mr Salvatore Sgro",
      "Dr Daniel Abbodanza",
      "Mr Sascha Hein",
      "Dr Stefen Paul",
      "Mr Nicola Pietrobon",
    ],
  },
  {
    image: "/8-724x1024.png",
    description: "2008 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2008-annual-conference",
    pageHeader: "Ultimate Dentistry is Aesthetics Scientific Meeting 2008",
    heading: "Ultimate Dentistry is Aesthetic",
    venue: "De Vere Belton Woods Hotel and Resort, Grantham, Lincolnshire",
    date: "10th & 11th October 2008",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Dr Avijit Banerjee",
      "Dr Marcus Beschnidt",
      "Dr Diego Capri",
      "Dr Krzysztof Chmielewski",
      "Dr Massimo Fuzzi",
      "Dr Sonia Leziy",
      "Dr Brahm Miller",
      "Dr Arnd Peschke",
      "Dr Irena Sailer",
    ],
  },
  {
    image: "/BAAD-2007-768x310.jpeg",
    description: "2007 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2007-annual-conference",
    pageHeader:
      "From Basic Science to Aesthetic Outcome Scientific Meeting 2007",
    heading: "From Basic Science to Aesthetic Outcome",
    venue: "The Millennium Gloucester Hotel",
    date: "11th Oct – 13th Oct 2007",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Lyndon Cooper – U.S.A.",
      "Alessandro Devigus – Switzerland",
      "Frank Filser – Switzerland",
      "Mauro Fradeani – Italy",
      "Laura Frost – United Kingdom",
      "Walter Gebhard – Germany",
      " Peter Gehrke – Germany",
      "Linda Greenwall – United Kingdom",
      "Ivo Krecji – Switzerland",
      "Oliver Pontius – Germany",
      "Eddie Scher – United Kingdom",
      "Cherilyn Sheets – U.S.A.",
      "Roberto Spreafico – Italy",
      "Giovanni Zuchelli – Italy",
    ],
  },
  {
    image: "/BAAD-2006.jpeg",
    description: "2006 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2006-annual-conference",
    pageHeader: "Keys to Aesthetic Harmony Scientific Meeting 2006",
    heading: "Keys to Aesthetic Harmony",
    venue: "Marriott Forest of Arden Hotel & Country Club",
    date: "19 Oct – 21 Oct 2006",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Ed McLaren – U.S.A.",
      "Jonathan Lack – United Kingom",
      "Koray Feran – United Kingdom",
      "Michael Norton – United Kingdom",
      "Sanjay Sethi – United Kingdom",
      "Tony Laurie – United Kingdom",
      "Stefan Paul – Switzerland",
      "Jurg Willi – Switzerland",
    ],
  },
  {
    image: "/BAAD-2005.jpeg",
    description: "2005 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2005-annual-conference",
    pageHeader:
      "Aesthetic Dentistry - Past, Present and Future Scientific Meeting 2005",
    heading: "Aesthetic Dentistry - Past, Present & Future",
    venue: "The Millennium Gloucester Hotel",
    date: "29th Sept – 1st Oct 2005",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Bernard Touati – France",
      "Dario Adolfi – Brazil",
      "David Garber – U.S.A",
      "Dennis Rohner – Switzerland",
      "Didier Dietschi – Switzerland",
      "Ernst Hegenbarth – Germany",
      "Galip Gurel – Turkey",
      "Greg Vigoren – U.S.A.",
      "Hans-Peter Spielmann – Switzerland",
      "Henry Salama – U.S.A.",
      "John McLean OBE – United Kingdom",
      "Kony Meyenberg – Switzerland",
      "Nicolas Pietrobon – Switzerland",
      "Nigel Saynor – United Kingdom",
      "Nitzan Bichacho – Israel",
      "Rafi Romano – Israel",
      "Rino Burkhardt – Switzerland",
      "Tidu Mankoo – United Kingdom",
      "Walter Devoto – Italy",
    ],
  },
  {
    image: "/2-e1659344441553-768x543.png",
    description: "2004 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2004-annual-conference",
    pageHeader:
      "Achieving Aesthic Harmony through Team Dynamics Scientific Meeting 2004",
    heading: "Achieving Harmony through Team Dynamics",
    venue: "The Grand Hotel, Eastbourne, East Sussex",
    date: "5th – 7th November 2004",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Dr Gerard Chiche",
      "Mr Naoki Aiba",
      "Dr Andrea Bazzucchi",
      "Dr Tidu Mankoo",
      "Professor Piet Haers",
      "Dr David Klaff",
      "Mr Brian Conroy MBE",
      "Dr Ashok Sethi",
      "Mr Peter Sochor",
    ],
  },
  {
    image: "/BAAD-2003.jpeg",
    description: "2003 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2003-annual-conference",
    pageHeader: "Annual Scientific Meeting 2003",
    heading: "Annual Scientific Meeting 2003",
    venue: "The Hanover International Hotel",
    date: "13th – 15th November 2003",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Jean-Marc Etienne – France",
      "Michael Stiller – Germany",
      "Katrin Doring – Germany",
      "Francesco Mangani – Italy",
      "Domenico Masseroni – Italy",
      "Giuseppe Romeo – Italy",
      "Jose Ignacio Gamborena – Spain",
      "Carlo Marinello – Switzerland",
      "John Besford – United Kingdom",
      "John Hubbard – United Kingdom",
      "Robert Winter – U.S.A.",
    ],
  },
  {
    image: "/2001-768x543.png",
    description: "2001 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2001-annual-conference",
    pageHeader: "Annual Scientific Meeting 2001",
    heading: "Annual Scientific Meeting 2001",
    venue: "Celtic Manor, Newport, Gwent, Wales",
    date: "20th – 22th September 2001",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Dr Eric Van Dooren",
      "Mr Luc Rutten",
      "Mr Patrick Rutten",
      "Dr Gil Tirlet",
      "Dr Michael Stiller",
      "Dr Rafi Romano",
      "Dr Pascal Magne",
      "Dr Stefan Paul",
      "Dr Rino Burkhardt",
      "Dr Ken Greene",
      "Dr Gareth Jenkins",
      "Prof Tim Watson",
      "Dr Terry Green",
      "Mr Pinhas Adar",
      "Dr Louis Belinfante",
      "Dr Paul Fugazzotto",
    ],
  },
  {
    image: "/2000-768x543.png",
    description: "2000 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-2000-annual-conference",
    pageHeader: "Annual Scientific Meeting 2000",
    heading: "Annual Scientific Meeting 2000",
    venue: "Celtic Manor, Newport, Gwent, Wales",
    date: "18th – 21th May 2000",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Lloyd Miller",
      "Konrad Mayenberg",
      "Nasser Barghi",
      "Oded Bahad",
      "Sascha Jovanovic",
      "Jorg Strub",
      "Peter Scharer",
      "Henry Salama",
      "Maurice Salama",
      "Daniel Buser",
      "David Garber",
      "Mauro Fredeani",
      "Myron Nevins",
      "Gianno Ricci",
      "Maurizio Tonetti",
      "Willi Geller",
      "Richard Jacobsen",
      "Vincent Celenza",
      "Ernst Hagenbarth",
      "Albino Triaca",
      "Hanspeter Spielmann",
      "John Mclean",
      "John Besford",
      "Paul Lambrechts",
      "Didier Dietschi",
      "Lorenzo Vanini",
      "Ron Goldstein",
    ],
  },
  {
    image: "/1999-e1663334503826-768x543.png",
    description: "1999 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-1999-annual-conference",
    pageHeader: "Annual Scientific Meeting 1999",
    heading: "Annual Scientific Meeting 1999",
    venue: "Celtic Manor, Newport, Gwent, Wales",
    date: "14th – 16th October 1999",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Dr Bart Van Meerbeck",
      "Dr Newton Fahl",
      "Dr Jorge Strub",
      "Mr Ernst Hegenbarth",
      "Dr Nitzan Bichacho",
      "Dr Rafi Romano",
      "Dr John Mclean OBE",
      "Dr Tidu Mankoo",
      "Mr Carlo Nepute",
      "Dr Gareth Jenkins",
      "Mr Rikki Hunt",
      "Dr David Wrinkler",
      "Dr Pascal Zyman",
      "Dr Carlo Zappala",
      "Dr Valter Devoto",
      "Dr James Mellonig",
      "Dr Ed Mclaren",
    ],
  },
  {
    image: "/WhatsApp-Image-2022-09-21-at-4.41.05-PM-768x536.jpeg",
    description: "1998 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-1998-annual-conference",
    pageHeader: "Annual Scientific Meeting 1998",
    heading: "Annual Scientific Meeting 1998",
    venue: "Carden Park, Hotel, Golf Resort & Spa, Chester, Cheshire",
    date: "17th – 18th October 1998",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Dr David Klaff",
      "Dr Baldwin W. Marchack",
      "Professor Dr Sandro Palla",
      "Dr Lambert Flick",
      "Dr Didier Fillion",
      "Professor Ljubo M. Marion",
      "Nigel Saynor",
      "Dr Jan Pameijer",
      "Dr Ueli Grunder",
      "Dr Fritz Kopp",
      "Dr Richard Lazzara",
      "Mr Eugenio Buldrini",
      "Dr Abe Ingber",
      "Dr Robert Rifkin",
      "Mr Phillippe Gruat",
      "Mr Jean-Paul Jourdan Herwyn",
    ],
  },
  {
    image: "/5-e1663334455410.png",
    description: "1997 – Scientific Meeting",
    link: "british-academy-of-aesthetic-dentistry-1997-annual-conference",
    pageHeader: "Annual Scientific Meeting 1997",
    heading: "Annual Scientific Meeting 1997",
    venue: "Carden Park, Hotel, Golf Resort & Spa, Chester, Cheshire",
    date: "16th – 18th October 1997",
    upperPara: "Below are the speakers for this meeting:",
    speakers: [
      "Dr Konrad Meyenberg",
      "Dr Itzhak Shoher",
      "Dr Nitzan Bichacho",
      "Dr Codi Landsberg",
      "Dr Ashok Sethi",
      "Dr John Cawood",
      "Dr Hugh O’Donnell",
      "Dr Sascha Jovanovic",
      "Dr Michael Wise",
      "Mr Nicola Pietrobon",
      "Mr Peter Sochor",
      "Dr Bertrand Khayat",
      "Dr Jean-Luc Pruvost",
      "Dr Didier Dietschi",
      "Mr Aharon Whiteman",
      "Dr Mauro Fradeani",
      "Mr Roberto Iafrate",
      "Mr Anthony Laurie",
    ],
  },
];
export const ROUTABLE_CARDS: IWithLink[] = SCIENTIFIC_CARDS.filter(isRoutable);
export const MASTER_CLASSES_BANNER = {
  image: "/our-mission.jpg",
  heading: "Masterclasses",
};
export const MEMBERS_BANNER = {
  image: "/our-mission.jpg",
  heading: "Members",
};
export const EXECTIVE_COUNCIL_BANNER = {
  image: "/executive-council-header.jpg",
  heading: "Executive Council",
};
export const PAST_PRESIDENTS_BANNER = {
  image: "/past-presidents-header.jpg",
  heading: "Past Presidents",
};
export const ASSOCIATE_MEMBER_BANNER = {
  image: "/our-mission.jpg",
  heading: "Associate Membership",
};
export const MEMBERSHIP_BANNER = {
  image: "/our-mission.jpg",
  heading: "Membership",
};
export const FULL_MEMBER_BANNER = {
  image: "/full-member-header.jpg",
  heading: "Full Members Presentation Protocol",
};
export const HISTORY_BANNER = {
  image: "/history-of-baad-header.jpg",
  heading: "The History of BAAD",
};
export const LAM_BANNER = {
  image: "/lambert-fick-memorial-header.webp",
  heading: "Lambert Fick Memorial",
};
export const SCIENTIFIC_BANNER = {
  image: "/our-mission.jpg",
  heading: "Scientific Conferences",
};
export const ABOUT_US_BANNER = {
  image: "/aboutus-header.jpg",
  heading: "About Us",
};
export const TESTIMONIALS_BANNER = {
  image: "/testemonials-header.jpg",
  heading: "Testimonials",
};
export const EXECUTIVE_TEAM = [
  {
    image: "/Nik-Sethi.jpg",
    name: "Nik Sethi",
    jd: "President",
  },
  {
    image: "/Nik-Sisodia.jpg",
    name: "Nik Sisodia",
    jd: "Past President",
  },
  {
    image: "/Roy-Morris.jpg",
    name: "Roy Morris",
    jd: "President Elect",
  },
  {
    image: "/Fazeela-Khan-Osborne.jpg",
    name: "Fazeela Khan Osborne",
    jd: "Secretary",
  },
  {
    image: "/Elaine-Mo.jpg",
    name: "Elaine Mo",
    jd: "Treasurer",
  },
  {
    image: "/gurvinder-Bhirth.jpg",
    name: "Gurvinder Bhirth",
    jd: "Scientific Committee",
  },
  {
    image: "/dipesh-Parmar.jpg",
    name: "Dipesh Parmar",
    jd: "Scientific Committee",
  },
  {
    image: "/andrew-Chandrapal.jpg",
    name: "Andrew Chandrapal",
    jd: "Full Committee Member",
  },
  {
    image: "/jon-Ayres-1.jpg",
    name: "Jon Ayres",
    jd: "Trade Liaison & Co-opted Committee Member",
  },
  {
    image: "/penny-Sykes.jpg",
    name: "Penny Sykes",
    jd: "Executive Administrator",
  },
];
export const PRESIDENT_TEAM = [
  {
    image: "/Nik-Sethi.jpg",
    name: "Nik Sethi",
    jd: "President",
  },
  {
    image: "/Nik-Sisodia.jpg",
    name: "Nik Sisodia",
    jd: "Immediate Past President",
  },
  {
    image: "/Dr-Nadeem-Younis.jpg",
    name: "Dr Nadeem Younis",
    jd: "Past President",
  },
  {
    image: "/Dr-Rob-Oretti.jpg",
    name: "Dr Rob Oretti",
    jd: "Past President",
  },
  {
    image: "/Dr-Patrick-Holmes.jpg",
    name: "Dr Patrick Holmes",
    jd: "Past President",
  },
  {
    image: "/Dr-Sanjay-Sethi.jpg",
    name: "Dr Sanjay Sethi",
    jd: "Past President",
  },
  {
    image: "/Dr-Korey-Feran.png",
    name: "Dr Koray Feran",
    jd: "Past President",
  },
  {
    image: "/Dr-Gareth-Jenkins.jpg",
    name: "Dr David Winkler",
    jd: "Past President",
  },
  {
    image: "/Mr-Anthony-Laurie.jpg",
    name: "Mr Anthony Laurie",
    jd: "Past President",
  },
  {
    image: "/Dr-Shane-Gordon.jpg",
    name: "Dr Shane Gordon",
    jd: "Past President",
  },
  {
    image: "/Dr-Nigel-Saynor.jpg",
    name: "Dr Nigel Saynor",
    jd: "Past President",
  },
  {
    image: "/Mr-John-Hubbard.jpg",
    name: "Mr John Hubbard",
    jd: "Past President",
  },
  {
    image: "/Dr-Gareth-Jenkins.jpg",
    name: "Dr Gareth Jenkins",
    jd: "Past President",
  },
  {
    image: "/Dr-Tidu-Mankoo.jpg",
    name: "Dr Tidu Mankoo",
    jd: "Past President",
  },
  {
    image: "/Dr-David-Klaff.jpg",
    name: "Dr David Klaff",
    jd: "Past President",
  },
  {
    image: "/Dr-Lambert-Flick.jpg",
    name: "Dr Lambert Fick",
    jd: "Founding President",
  },
];
export const MEMBERS_DATA = [
  {
    firstname: "Orestis",
    surname: "Angeletos-Paparizos",
    memberType: "Associate",
    address: "Specialist Dental Services, 94 Harley Street",
    city: "London",
    country: "Town/City",
    postCode: "W1G 7HX",
    telephone: "0207 580 4200",
    email: "info@specialistdentalservices.com",
    link: "https://www.specialistdentalservices.com",
    website: "www.specialistdentalservices.com",
  },
  {
    firstname: "Billal",
    surname: "Arshad",
    memberType: "Associate",
    address: "Ruh Dental, Unit 5G, the Avenue, Spinningfields",
    city: "Manchester",
    country: "Grt Manchester",
    postCode: "M3 3FL",
    telephone: "0161 348 8738",
    email: "manchester@ruhdental.com",
    link: "https://www.www.ruhdental.com",
    website: "www.ruhdental.com",
  },
  {
    firstname: "Jon",
    surname: "Ayres",
    memberType: "Associate",
    address: "Cowbridge Dental Practice, 30 High Street",
    city: "Cowbridge",
    country: "Vale of Glamorgan",
    postCode: "CF71 7AG",
    telephone: "01446 773 284",
    email: "info@cowbridgedental.com",
    link: "https://www.cowbridgedental.com",
    website: "www.cowbridgedental.com",
  },
  {
    firstname: "Moira",
    surname: "Baldiraghi",
    memberType: "Associate",
    address: "92 Dental, 5 Glenthorne Mews, 115A Glenthorne Road",
    city: "London",
    country: "London",
    postCode: "W6 0LJ",
    telephone: "020 8748 1381",
    email: "01708 740372",
    link: "https://www.92dental.co.uk",
    website: "www.92dental.co.uk",
  },
  {
    firstname: "Iain",
    surname: "Baldwin",
    memberType: "Associate",
    address: "Nexus Dental Laboratory, 18 Raglan Street",
    city: "Harrogate",
    country: "North Yorkshire",
    postCode: "HG1 1LE",
    telephone: "01423 561392",
    email: "iain.baldwin@nexus.dental",
    link: "https://www.nexus.dental",
    website: "www.nexus.dental",
  },
  {
    firstname: "Tariq",
    surname: "Bashir",
    memberType: "Full",
    address: "Visage, 61 Miller Street",
    city: "Glasgow",
    country: "Glasgow",
    postCode: "G1 1EB",
    telephone: "0141 222 6580",
    email: "GlasgowVisage@bupadentalcare.co.uk",
    website: "",
    link: "",
  },
  {
    firstname: "Simon",
    surname: "Belford",
    memberType: "Full",
    address: "Alington Dental, 7 Poole Road",
    city: "Bournemouth",
    country: "Dorset",
    postCode: "BH2 5QR",
    telephone: "01202 763 348",
    email: "info@bridgedentalpractice.com",
    website: "",
    link: "",
  },
  {
    firstname: "John",
    surname: "Besford",
    memberType: "Life",
    address: "RETIRED",
    city: "Belmore Dental, 16 Belmore Street",
    country: "Enniskillen",
    postCode: "Northern Ireland",
    telephone: "BT74 6AA",
    email: "028 6632 9222",
    website: "tco@belmoredental.co.uk",
    link: "https://tco@belmoredental.co.uk",
  },
  {
    firstname: "Gurvinder",
    surname: "Bhirth",
    memberType: "Full",
    address: "Carriage Works Dental, The Old Carriage Works, Brunel Quays",
    city: "Lostwithiel",
    country: "Cornwall",
    postCode: "PL22 0EN",
    telephone: "01208 873116",
    email: "enquiries@carriageworksdental.co.uk",
    website: "",
    link: "",
  },
  {
    firstname: "Patrick",
    surname: "Bottom",
    memberType: "Life",
    address: "RETIRED",
    city: "Sardinia House Dental Practice, 4th Floor Sardinia House, 52 Sardinia Street",
    country: "London",
    postCode: "London",
    telephone: "WC2A 3LZ",
    email: "020 7404 8600",
    website: "amit@sardiniadental.com",
    link: "https://amit@sardiniadental.com",
  },
  {
    firstname: "Steven",
    surname: "Campbell",
    memberType: "Full",
    address: "Nexus Dental Laboratory, 18 Raglan Street",
    city: "Harrogate",
    country: "Chelmsford",
    postCode: "HG1 1LE",
    telephone: "01423 561392",
    email: "steve.campbell@nexus.dental",
    website: "www.nexus.dental",
    link: "https://www.nexus.dental",
  },
  {
    firstname: "Julian",
    surname: "Caplan",
    memberType: "Full",
    address: "Aviva Dentistry Ltd, 101 St Peters Street",
    city: "St Albans",
    country: "Hertfordshire",
    postCode: "AL1 3EN",
    telephone: "01727 854429",
    email: "info@avivacosmeticdentistry.co.uk",
    website: "",
    link: "",
  },
  {
    firstname: "Anmol",
    surname: "Chander",
    memberType: "Associate",
    address: "The Staines Center of Dental Excellence, 35 Kingston Road",
    city: "Staines",
    country: "Middlesex",
    postCode: "TW18 4ND",
    telephone: "01784 466325",
    email: "reception@stcode.co.uk",
    website: "www.stcode.co.uk",
    link: "https://www.stcode.co.uk",
  },
  {
    firstname: "Andrew",
    surname: "Chandrapal",
    memberType: "Full",
    address: "Bourne End Dental Clinic, 1 Station Road, Wooburn Green",
    city: "Bourne End",
    country: "Buckinghamshire",
    postCode: "SL8 5QF",
    telephone: "01628 523353",
    email: "mail@bourneenddental.co.uk",
    website: "www.bourneenddental.co.uk",
    link: "https://www.bourneenddental.co.uk",
  },
  {
    firstname: "Tomi",
    surname: "Ciocan",
    memberType: "Full",
    address: "Nicolescu-Agatstein Dental Clinique, Primaverii Str. No 24",
    city: "Bucharest",
    country: "Romania",
    postCode: "14192",
    telephone: "0040 731 400851",
    email: "",
    website: "",
    link: "",
  },
  {
    firstname: "Stuart",
    surname: "Crook",
    memberType: "Associate",
    address: "Kendal Dental Care, 56 Stramongate",
    city: "Kendal",
    country: "Cumbria",
    postCode: "LA9 4BD",
    telephone: "01539 720302",
    email: "info@kendaldentalcare.co.uk",
    website: "",
    link: "",
  },
  {
    firstname: "Andrew",
    surname: "Denny",
    memberType: "Full",
    address: "Twenty 2 Dental, 22 Milton Road",
    city: "Weston Super-Mare",
    country: "Somerset",
    postCode: "BS23 2SL",
    telephone: "01934 620220",
    email: "info@twenty2dental.com",
    website: "www.twenty2dental.com",
    link: "https://www.twenty2dental.com",
  },
  {
    firstname: "Rebecca",
    surname: "Denny",
    memberType: "Associate",
    address: "Twenty 2 Dental, 22 Milton Road",
    city: "Weston Super-Mare",
    country: "Somerset",
    postCode: "BS23 2SL",
    telephone: "01934 620220",
    email: "info@twenty2dental.com",
    website: "www.twenty2dental.com",
    link: "https://www.twenty2dental.com",
  },
  {
    firstname: "Andrew",
    surname: "Fennell",
    memberType: "Full",
    address: "Winning Smiles Dental Surgery, 1 The Parade, Colchester Road",
    city: "Harold Park",
    country: "Essex",
    postCode: "RM3 0AQ",
    telephone: "01708 371223",
    email: "afennell@winning-smiles.co.uk",
    website: "www.winning-smiles.co.uk",
    link: "https://www.winning-smiles.co.uk",
  },
  {
    firstname: "Koray",
    surname: "Feran",
    memberType: "Full",
    address:
      "The London Centre for Implant and Aesthetic Dentistry, 28 Wimpole St",
    city: "London",
    country: "",
    postCode: "W1G 8GW",
    telephone: "0207 323 3041",
    email: "koray@lciad.co.uk",
    website: "www.lciad.co.uk",
    link: "https://www.lciad.co.uk",
  },
  {
    firstname: "Eva",
    surname: "Forst",
    memberType: "Full",
    address:
      "Fusion Dental Laboratory Ltd, 38B Kingfisher Court, Hambridge Road",
    city: "Newbury",
    country: "Berkshire",
    postCode: "RG14 5SJ",
    telephone: "01635 237 755",
    email: "info@fusiondental.com",
    website: "www.fusiondental.com",
    link: "https://www.fusiondental.com",
  },
  {
    firstname: "Yasmin",
    surname: "George",
    memberType: "Full",
    address:
      "Confident Smiles by Design, Oatlands Dental Lounge, 127a Oatlands Drive, 1st Floor, Alfred House",
    city: "Weybridge",
    country: "Surrey",
    postCode: "KT13 9LB",
    telephone: "01932 858656",
    email: "info@confidentsmiles.org",
    website: "www.confidentsmiles.org",
    link: "https://www.confidentsmiles.org",
  },
  {
    firstname: "Massimo",
    surname: "Giovarruscio",
    memberType: "Full",
    address: "Bristol Endodontic Clinic, 9 North View",
    city: "Bristol",
    country: "Bristol",
    postCode: "BS6 7PT",
    telephone: "01179 238 400",
    email: "info@rootfillings.com",
    website: "www.rootfillings.com",
    link: "https://www.rootfillings.com",
  },
  {
    firstname: "Shane",
    surname: "Gordon",
    memberType: "Full",
    address: "St Peter's Dental Practice, 32 High Street, St. Peter's",
    city: "Broadstairs",
    country: "Kent",
    postCode: "CT10 2TQ",
    telephone: "01843 860 825",
    email: "shane.gordon@foreversmile.co.uk",
    website: "www.foreversmile.co.uk",
    link: "https://www.foreversmile.co.uk",
  },
  {
    firstname: "Alex",
    surname: "Hadley",
    memberType: "Associate",
    address: "Dental Beauty Romford, 167A North Street",
    city: "Romford",
    country: "Essex",
    postCode: "RM1 1DT",
    telephone: "01708 740372",
    email: "info@dentalbeautyromford.co.uk",
    website: "",
    link: "",
  },
  {
    firstname: "Elaine",
    surname: "Halley",
    memberType: "Associate",
    address: "Cherrybank Dental Spa, 168 Glasgow Road",
    city: "Perth",
    country: "Perth & Kinross",
    postCode: "PH2 0LY",
    telephone: "01738 624667",
    email: "info@cherrydental.com",
    website: "",
    link: "",
  },
  {
    firstname: "Ognedal",
    surname: "Hans Kristian",
    memberType: "Associate",
    address: "Kongsgata 44",
    city: "Stavanger",
    country: "Norway",
    postCode: "4005",
    telephone: "00 47 51 51 0317",
    email: "post@bratann.no",
    website: "",
    link: "",
  },
  {
    firstname: "Patrick",
    surname: "Holmes",
    memberType: "Full",
    address:
      "Seven Fields Dental & Health Centre, Groundwell Farm, Woodcutters Mews",
    city: "Swindon",
    country: "Wiltshire",
    postCode: "SN25 4AU",
    telephone: "01793 722 194",
    email: "Pat@sevenfields.co.uk",
    website: "ceo.Pat@sevenfields.sm.td",
    link: "https://ceo.Pat@sevenfields.sm.td",
  },
  {
    firstname: "John",
    surname: "Hubbard",
    memberType: "Life",
    address: "John Hubbard Dental Studio, Greenwich House, Peel Street",
    city: "Maidstone",
    country: "Kent",
    postCode: "ME14 2BP",
    telephone: "01622 677769",
    email: "jhdental@aol.com",
    website: "",
    link: "",
  },
  {
    firstname: "Dhanish",
    surname: "Jabbar",
    memberType: "Associate",
    address: "Bridge Dental Practice, 2 Colne Road",
    city: "Burnley",
    country: "Lancashire",
    postCode: "BB10 1LA",
    telephone: "01282 423973",
    email: "info@bridgedentalpractice.com",
    website: "",
    link: "",
  },
  {
    firstname: "Gareth",
    surname: "Jenkins",
    memberType: "Life",
    address: "RETIRED",
    city: "",
    country: "",
    postCode: "",
    telephone: "",
    email: "",
    website: "",
    link: "",
  },
  {
    firstname: "Stephen",
    surname: "Jones",
    memberType: "Life",
    address: "RETIRED",
    city: "",
    country: "",
    postCode: "",
    telephone: "",
    email: "",
    website: "",
    link: "",
  },
  {
    firstname: "Harmit",
    surname: "Kalsi",
    memberType: "Associate",
    address: "Teddington Dental Practice, 2 Gloucester Road, Teddington",
    city: "London",
    country: "London",
    postCode: "TW11 0NU",
    telephone: "020 8977 2911",
    email: "hsk@sheendental.co.uk",
    website: "www.sheendental.co.uk",
    link: "https://www.sheendental.co.uk",
  },
  {
    firstname: "Manraj",
    surname: "Kalsi",
    memberType: "Associate",
    address: "Teddington Dental Practice, 2 Gloucester Road, Teddington",
    city: "London",
    country: "London",
    postCode: "TW11 0NU",
    telephone: "020 8977 2911",
    email: "msk@sheendental.co.uk",
    website: "www.sheendental.co.uk",
    link: "https://www.sheendental.co.uk",
  },
  {
    firstname: "David",
    surname: "Kaplan",
    memberType: "Life",
    address: "RETIRED",
    city: "",
    country: "",
    postCode: "",
    telephone: "",
    email: "",
    website: "",
    link: "",
  },
  {
    firstname: "Des",
    surname: "Kelly",
    memberType: "Associate",
    address:
      "Fusion Dental Laboratory Ltd, 38B Kingfisher Court, Hambridge Road",
    city: "Newbury",
    country: "Berkshire",
    postCode: "RG14 5SJ",
    telephone: "01635 237 755",
    email: "info@fusiondental.com",
    website: "www.fusiondental.com",
    link: "https://www.fusiondental.com",
  },
  {
    firstname: "Fazeela",
    surname: "Khan-Osborne",
    memberType: "Full",
    address: "One to One Dental Implant Clinic, 80 Harley Street",
    city: "London",
    country: "London",
    postCode: "W1G 7HL",
    telephone: "0207 486 0000",
    email: "fazeela@121dental.co.uk",
    website: "www.121dental.co.uk",
    link: "https://www.121dental.co.uk",
  },
  {
    firstname: "Sripal",
    surname: "Kumar",
    memberType: "Associate",
    address:
      "Platinum Dental Care, Port East Building, West India Quay, Hersmere Road, Canary Wharf",
    city: "London",
    country: "London",
    postCode: "E14 4AE",
    telephone: "020 7531 1717",
    email: "info@platinumdentalcare.co.uk",
    website: "www.platinumdentalcare.co.uk",
    link: "https://www.platinumdentalcare.co.uk",
  },
  {
    firstname: "Asad",
    surname: "Lalloo",
    memberType: "Associate",
    address: "Smile Impressions, 257 Shooters Hill Road, Blackheath",
    city: "London",
    country: "London",
    postCode: "SE3 8UN",
    telephone: "0203 621 2260",
    email: "info@dentalbeautyblackheath.co.uk",
    website: "www.dentalbeautyblackheath.co.uk",
    link: "https://www.dentalbeautyblackheath.co.uk",
  },
  {
    firstname: "Anthony",
    surname: "Laurie",
    memberType: "Full",
    address: "Dental Excellence Ltd., 1 Bow Lane",
    city: "London",
    country: "London",
    postCode: "EC4M 9EE",
    telephone: "0207 248 2180",
    email: "anthony@dentalexcellencetech.com",
    website: "www.dentalexcellencetech.com",
    link: "https://www.dentalexcellencetech.com",
  },
  {
    firstname: "Tidu",
    surname: "Mankoo",
    memberType: "Full",
    address:
      "Windsor Centre for Advanced Dentistry, Dorset House, 1 Dorset Road",
    city: "Windsor",
    country: "Berkshire",
    postCode: "SL4 3BA",
    telephone: "01753 833755",
    email: "tidu@advanceddentistry.co.uk",
    website: "www.advanceddentistry.co.uk",
    link: "https://www.advanceddentistry.co.uk",
  },
  {
    firstname: "Ljubo",
    surname: "Marion",
    memberType: "Life",
    address: "RETIRED",
    city: "",
    country: "",
    postCode: "",
    telephone: "",
    email: "",
    website: "",
    link: "",
  },
  {
    firstname: "Quentin",
    surname: "McCoach",
    memberType: "Associate",
    address: "Addison Place Dental Practice, 21 Addison Place, Holland Park",
    city: "London",
    country: "London",
    postCode: "W11 4RJ",
    telephone: "0207 602 1856",
    email: "info@addisonplace.co.uk",
    website: "www.addisonplace.co.uk",
    link: "https://www.addisonplace.co.uk",
  },
  {
    firstname: "Sinead",
    surname: "McEnhill",
    memberType: "Associate",
    address: "Belmore Dental, 16 Belmore Street",
    city: "Enniskillen",
    country: "Northern Ireland",
    postCode: "BT74 6AA",
    telephone: "028 6632 9222",
    email: "tco@belmoredental.co.uk",
    website: "",
    link: "",
  },
  {
    firstname: "Nikita",
    surname: "Mehta",
    memberType: "Associate",
    address:
      "West House Dental Practice, 2nd Floor, West House, 50 West End Lane",
    city: "Pinner",
    country: "Middlesex",
    postCode: "HA5 1AE",
    telephone: "020 8866 3025",
    email: "hello@westhousedental.com",
    website: "",
    link: "",
  },
  {
    firstname: "Shubham",
    surname: "Mittal",
    memberType: "Associate",
    address:
      "Clifton Moor Dental Centre, Tower Court Health Centre, Oakdale Road",
    city: "York",
    country: "North Yorkshire",
    postCode: "YO30 4RZ",
    telephone: "01904 479777",
    email: "cmdental.implantcentre@gmail.com",
    website: "www.cmdental.co.uk",
    link: "https://www.cmdental.co.uk",
  },
  {
    firstname: "Basil",
    surname: "Mizrahi",
    memberType: "Full",
    address: "Basil Mizrahi Prosthodontics, 38 Harmont House, 20 Harley Street",
    city: "London",
    country: "London",
    postCode: "W1G 9PJ",
    telephone: "0207 436 3194",
    email: "info@basilmizrahi.co.uk",
    website: "www.basilmizrahi.co.uk",
    link: "https://www.basilmizrahi.co.uk",
  },
  {
    firstname: "Elaine",
    surname: "Mo",
    memberType: "Associate",
    address: "Ridgway Dental, 71 Ridgway, Wimbledon",
    city: "London",
    country: "London",
    postCode: "SW19 4SS",
    telephone: "020 8946 2255",
    email: "info@ridgwaydental.co.uk",
    website: "www.ridgwaydental.co.uk",
    link: "https://www.ridgwaydental.co.uk",
  },
  {
    firstname: "Roy",
    surname: "Morris",
    memberType: "Full",
    address: "Dental & Implant Excellence, 67 Ombersley Street East",
    city: "Droitwich Spa",
    country: "Worcestershire",
    postCode: "WR9 8QS",
    telephone: "01905 778873",
    email: "roy@excellence-in-dentistry.co.uk",
    website: "www.excellence-in-dentistry.co.uk",
    link: "https://www.excellence-in-dentistry.co.uk",
  },
  {
    firstname: "Denise",
    surname: "Ngsiad",
    memberType: "Associate",
    address: "Darrell House Dental Practice, 85 West Street",
    city: "Dunstable",
    country: "Bedfordshire",
    postCode: "LU6 1SE",
    telephone: "01582 601 351",
    email: "appointments@darrellhousedental.co.uk",
    website: "",
    link: "",
  },
  {
    firstname: "Eimear",
    surname: "O’Connell",
    memberType: "Associate",
    address: "Bite Dentistry, 30 Glen Street",
    city: "Edinburgh",
    country: "Scotland",
    postCode: "EH3 9JE",
    telephone: "0131 22804030",
    email: "Eimear@bitedentistry.co.uk",
    website: "www.bitedentistry.co.uk",
    link: "https://www.bitedentistry.co.uk",
  },
  {
    firstname: "Robert",
    surname: "Oretti",
    memberType: "Full",
    address: "Pentangle Dental Transformations, Park Street",
    city: "Newbury",
    country: "Berkshire",
    postCode: "RG14 1EA",
    telephone: "01635 550353",
    email: "robert.oretti@bupadentalcare.co.uk",
    website: "www.bupadentalcare.co.uk",
    link: "https://www.bupadentalcare.co.uk",
  },
  {
    firstname: "Dipesh",
    surname: "Parmar",
    memberType: "Full",
    address: "Acorn Dental, 208 Swanshurst Lane, Moseley",
    city: "Birmingham",
    country: "West Midlands",
    postCode: "B13 0AW",
    telephone: "0121 777 1537",
    email: "dipesh@acorndental.co.uk",
    website: "www.acorndental.co.uk",
    link: "https://www.acorndental.co.uk",
  },
  {
    firstname: "Neilesh",
    surname: "Paryani",
    memberType: "Associate",
    address: "Oatlands Dental Lounge, 127a Oatlands Drive",
    city: "Weybridge",
    country: "Surrey",
    postCode: "KT13 9LB",
    telephone: "01932 585686",
    email: "info@oatlandsdentallounge.com",
    website: "www.oatlandsdentallounge.com",
    link: "https://www.oatlandsdentallounge.com",
  },
  {
    firstname: "Amie",
    surname: "Patel",
    memberType: "Associate",
    address: "Bridge Dental, 91 Borough High Street, London Bridge",
    city: "London",
    country: "London",
    postCode: "SE1 1NL",
    telephone: "020 7407 2174",
    email: "info@bridgedental.com",
    website: "www.bridgedental.com",
    link: "https://www.bridgedental.com",
  },
  {
    firstname: "Amit",
    surname: "Patel",
    memberType: "Associate",
    address:
      "Sardinia House Dental Practice, 4th Floor Sardinia House, 52 Sardinia Street",
    city: "London",
    country: "London",
    postCode: "WC2A 3LZ",
    telephone: "020 7404 8600",
    email: "amit@sardiniadental.com",
    website: "",
    link: "",
  },
  {
    firstname: "Amit",
    surname: "Patel",
    memberType: "Associate",
    address:
      "Brickfields Dental Care, 1st Floor, 10 Brickfields Road, South Woodham Ferrers",
    city: "Chelmsford",
    country: "Essex",
    postCode: "CM3 5XB",
    telephone: "01245 328060",
    email: "info@brickfieldsdentalcare.co.uk",
    website: "",
    link: "",
  },
  {
    firstname: "Hiral",
    surname: "Patel",
    memberType: "Associate",
    address: "Dentaria, 19 Glenshiel Road, Eltham",
    city: "London",
    country: "London",
    postCode: "SE9 1AQ",
    telephone: "020 8294 3081",
    email: "info@dentaria.co.uk",
    website: "www.dentaria.co.uk",
    link: "https://www.dentaria.co.uk",
  },
  {
    firstname: "Rahul",
    surname: "Patel",
    memberType: "Associate",
    address: "Great Dunmow Dental Care, 40A High Street",
    city: "Great Dunmow",
    country: "Essex",
    postCode: "CM6 1AH",
    telephone: "01371 875 116",
    email: "infp@greatdunmowdentalcare.co.uk",
    website: "www.greatdunmowdentalcare.co.uk",
    link: "https://www.greatdunmowdentalcare.co.uk",
  },
  {
    firstname: "André Philip",
    surname: "Pettemerides",
    memberType: "Full",
    address:
      "Edgar Buildings Dental & Implant Clinic, Edgar Buildings, 7 Edgar Buildings",
    city: "Bath",
    country: "Somerset",
    postCode: "BA1 2EE",
    telephone: "01225 466086",
    email: "info@smileofconfidence.com",
    website: "www.smileofconfidence.com",
    link: "https://www.smileofconfidence.com",
  },
  {
    firstname: "Shameek",
    surname: "Popat",
    memberType: "Associate",
    address: "Rosebank Dental Practice, Shire Lane, Chorley Wood",
    city: "Chorley Wood",
    country: "Herts",
    postCode: "WD3 5NH",
    telephone: "01923 282691",
    email: "info@rosebankdental.co.uk",
    website: "www.rosebankdental.co.uk",
    link: "https://www.rosebankdental.co.uk",
  },
  {
    firstname: "Ivo",
    surname: "Raitchev",
    memberType: "Associate",
    address: "Cherry Tree Dental Care, 93 Robin Hood Way, Kingston Vale",
    city: "London",
    country: "",
    postCode: "SW15 3QE",
    telephone: "0208 617 9180",
    email: "ivo@cherrytreedentistry.co.uk",
    website: "www.cherrytreedentistry.co.uk",
    link: "https://www.cherrytreedentistry.co.uk",
  },
  {
    firstname: "Nadia",
    surname: "Raitchev",
    memberType: "Associate",
    address: "Cherry Tree Dental Care, 93 Robin Hood Way, Kingston Vale",
    city: "London",
    country: "",
    postCode: "SW15 3QE",
    telephone: "0208 617 9180",
    email: "nadia@cherrytreedentistry.co.uk",
    website: "www.cherrytreedentistry.co.uk",
    link: "https://www.cherrytreedentistry.co.uk",
  },
  {
    firstname: "Jacqueline",
    surname: "Rasic",
    memberType: "Associate",
    address: "Happident, Engelbrektsgatan 7",
    city: "Malmo",
    country: "",
    postCode: "21133",
    telephone: "",
    email: "tandkliniken@yahoo.com",
    website: "www.happident.se",
    link: "https://www.happident.se",
  },
  {
    firstname: "Nigel",
    surname: "Saynor",
    memberType: "Full",
    address:
      "Bramcote Dental Practice and Dental Implant Centre, 3 Syddal Road, Bramhall",
    city: "Stockport",
    country: "Cheshire",
    postCode: "SK7 1AB",
    telephone: "0161 439 4247",
    email: "pm@smiledoc.co.uk",
    website: "www.smiledoc.co.uk",
    link: "https://www.smiledoc.co.uk",
  },
  {
    firstname: "Tristan",
    surname: "Scott",
    memberType: "Associate",
    address: "The Practice at The General, 1 Lower Guinea Street",
    city: "Bristol",
    country: "",
    postCode: "BS1 6SY",
    telephone: "0117 405 4364",
    email: "tristan@practicegeneral.co.uk",
    website: "www.practicegeneral.co.uk",
    link: "https://www.practicegeneral.co.uk",
  },
  {
    firstname: "Nik",
    surname: "Sethi",
    memberType: "Full",
    address: "Square Mile Dental Centre, 7 White Kennett Street",
    city: "London",
    country: "London",
    postCode: "E1 7BS",
    telephone: "0207 377 0990",
    email: "info@squaremiledentalcentre.co.uk",
    website: "www.squaremiledentalcentre.co.uk",
    link: "https://www.squaremiledentalcentre.co.uk",
  },
  {
    firstname: "Sanjay",
    surname: "Sethi",
    memberType: "Full",
    address: "Square Mile Dental Centre, 7 White Kennett Street",
    city: "London",
    country: "London",
    postCode: "E1 7BS",
    telephone: "0207 377 0990",
    email: "info@squaremiledentalcentre.co.uk",
    website: "www.squaremiledentalcentre.co.uk",
    link: "https://www.squaremiledentalcentre.co.uk",
  },
  {
    firstname: "Gizem",
    surname: "Seymenoglu",
    memberType: "Associate",
    address: "Longevita, 42 New Kings Road",
    city: "London",
    country: "",
    postCode: "SW6 4LS",
    telephone: "020 3409 1947",
    email: "info@longevitahealth.com",
    website: "www.longevitahealth.com",
    link: "https://www.longevitahealth.com",
  },
  {
    firstname: "Dhruv",
    surname: "Shah",
    memberType: "Associate",
    address: "The Smile Clinic, 39 St Botolphs Street",
    city: "Colchester",
    country: "Essex",
    postCode: "CO2 7EA",
    telephone: "01206 767471",
    email: "enquiries@thesmileclinic.uk.com",
    website: "www.thesmileclinic.uk.com",
    link: "https://www.thesmileclinic.uk.com",
  },
  {
    firstname: "Vishaal",
    surname: "Shah",
    memberType: "Associate",
    address: "Dentality Ltd, Unit 1–3 Tudor Hall, Conduit Lane",
    city: "Hoddesden",
    country: "Hertfordshire",
    postCode: "EN11 8FN",
    telephone: "01992 462345",
    email: "dentalitylimited@gmail.com",
    website: "www.dentality.co.uk",
    link: "https://www.dentality.co.uk",
  },
  {
    firstname: "Rajiv",
    surname: "Sheth",
    memberType: "Associate",
    address: "Hacton Dental Care, 1 Hacton Lane",
    city: "Hornchurch",
    country: "Essex",
    postCode: "RM12 6PJ",
    telephone: "01708 447063",
    email: "info@hactondentalcare.com",
    website: "www.hactondentalcare.com",
    link: "https://www.hactondentalcare.com",
  },
  {
    firstname: "Nik",
    surname: "Sisodia",
    memberType: "Full",
    address: "Ten Dental, 10 The Pavement",
    city: "Clapham",
    country: "London",
    postCode: "SW4 0HY",
    telephone: "0207 622 7610",
    email: "nik@tendental.com",
    website: "www.tendental.com",
    link: "https://www.tendental.com",
  },
  {
    firstname: "Payman",
    surname: "Sobhani",
    memberType: "Associate",
    address: "104 Harley Street",
    city: "London",
    country: "London",
    postCode: "W1G 7JD",
    telephone: "",
    email: "",
    website: "",
    link: "",
  },
  {
    firstname: "Lara",
    surname: "Stangacilovic",
    memberType: "Full",
    address: "Nicolescu–Agatstein Dental Clinique, Primaverii Str. No 24",
    city: "Bucharest",
    country: "Romania",
    postCode: "14192",
    telephone: "00 40 735 785894",
    email: "write@drlara.dentist",
    website: "www.drlara.dentist",
    link: "https://www.drlara.dentist",
  },
  {
    firstname: "Finlay",
    surname: "Sutton",
    memberType: "Full",
    address: "Garstang Dental Referral Practice, Weind House, Par Hill Road",
    city: "Garstang",
    country: "Lancashire",
    postCode: "PR3 1EL",
    telephone: "01995 606091",
    email: "office@garstangdrp.co.uk",
    website: "www.garstangdrp.co.uk",
    link: "https://www.garstangdrp.co.uk",
  },
  {
    firstname: "Jurgita",
    surname: "Sybaite",
    memberType: "Full",
    address: "38 Harmont House, 20 Harley Street",
    city: "London",
    country: "",
    postCode: "W1G 9PJ",
    telephone: "07500 931261",
    email: "reception@basilmizrahi.co.uk",
    website: "www.basilmizrahi.co.uk",
    link: "https://www.basilmizrahi.co.uk",
  },
  {
    firstname: "Thomas",
    surname: "Telfer",
    memberType: "Full",
    address: "Nexus Dental Laboratory, 18 Raglan Street",
    city: "Harrogate",
    country: "North Yorkshire",
    postCode: "HG1 1LE",
    telephone: "01423 561392",
    email: "info@nexus.dental",
    website: "www.nexus.dental",
    link: "https://www.nexus.dental",
  },
  {
    firstname: "Mete",
    surname: "Ucer",
    memberType: "Associate",
    address: "Notley Dental Care, 17 Ockford Road",
    city: "Godalming",
    country: "Surrey",
    postCode: "GU7 1QU",
    telephone: "01483 417102",
    email: "info@notleydentalcare.co.uk",
    website: "www.notleydentalcare.co.uk",
    link: "https://www.notleydentalcare.co.uk",
  },
  {
    firstname: "Devin",
    surname: "Vaghela",
    memberType: "Associate",
    address: "The Bristol Dental Practice, 1 Queen Square",
    city: "Bristol",
    country: "",
    postCode: "BS1 4JQ",
    telephone: "0117 405 4364",
    email: "",
    website: "www.thebristoldentist.co.uk",
    link: "https://www.thebristoldentist.co.uk",
  },
  {
    firstname: "Shernaz",
    surname: "Wadia",
    memberType: "Associate",
    address: "Longborough Dental Practice, Reigate Road",
    city: "Dorking",
    country: "Surrey",
    postCode: "RH4 1QE",
    telephone: "",
    email: "",
    website: "www.longboroughdental.co.uk",
    link: "https://www.longboroughdental.co.uk",
  },
  {
    firstname: "Martin",
    surname: "Wanendeya",
    memberType: "Full",
    address: "Ten Dental, 10 The Pavement",
    city: "Clapham",
    country: "London",
    postCode: "SW4 0HY",
    telephone: "020 8138 8623",
    email: "martin@tendental.com",
    website: "www.tendental.com",
    link: "https://www.tendental.com",
  },
  {
    firstname: "Juerg",
    surname: "Willi",
    memberType: "Full",
    address: "Seidenstrasse 6",
    city: "Lachen",
    country: "Switzerland",
    postCode: "CH 8853",
    telephone: "055 442 7433",
    email: "rezeption@zahnarzt-lachen.ch",
    website: "www.zahnarzt-lachen.ch",
    link: "https://www.zahnarzt-lachen.ch",
  },
  {
    firstname: "David",
    surname: "Winkler",
    memberType: "Life",
    address: "RETIRED",
    city: "",
    country: "",
    postCode: "",
    telephone: "",
    email: "",
    website: "",
    link: "",
  },
  {
    firstname: "Riaz",
    surname: "Yar",
    memberType: "Full",
    address: "Square Advanced Dental Care, 2 Hollins House, 329 Hale Road",
    city: "Hale Barns",
    country: "Manchester",
    postCode: "WA15 8TF",
    telephone: "0161 980 9730",
    email: "info@thesquaredental.com",
    website: "www.thesquaredental.com",
    link: "https://www.thesquaredental.com",
  },
  {
    firstname: "Nadeem",
    surname: "Younis",
    memberType: "Full",
    address: "Bridge Dental Practice, 2 Colne Road",
    city: "Burnley",
    country: "Lancashire",
    postCode: "BB10 1LA",
    telephone: "01282 423973",
    email: "info@bridgedentalpractice.com",
    website: "www.bridgedentalpractice.com",
    link: "https://www.bridgedentalpractice.com",
  },
  {
    firstname: "Monder",
    surname: "Zbaeda",
    memberType: "Associate",
    address: "Barrington Dental Care, 23A Barrington Road",
    city: "Altrincham",
    country: "Cheshire",
    postCode: "WA14 1HP",
    telephone: "0161 928 0014",
    email: "info@barringtondental.co.uk",
    website: "www.barringtondental.co.uk",
    link: "https://www.barringtondental.co.uk",
  },
];
export const ABOUT_SAME_SECTION = [
  {
    // heading: "Organisation",
    // para: "The Academy is a non-profit organisation and no part of net earnings, if any, shall inure to the benefit of any person. The Academy earnings are devoted exclusively to the uses and purposes of the Academy as defined in the foregoing section.",
    para: "Founding leaders such as Lambert Fick, David Klaff, David Kaplan and Dave Winkler to name but a few, as inspirational visionaries forged a path for clinicians who were defined by their excellence and dedication to the highest professional, scientific, artistic and ethical standards in dentistry, encompassing research, publications and educational presentations.",
    image: "/organisation.webp",
    imageOne: "/sliding-image.webp",
  },
  {
    // heading: "Meetings",
    para: "BAAD is now recognised as one of the leading organisations in the world, known for its Scientific Meetings and Masterclass events. These are held in beautiful locations that bring people together to learn, connect, and build lasting relationships - creating a close-knit ‘dental family’ of like-minded professionals. Here, camaraderie and the sharing of knowledge form the foundation of a respected community of Aesthetic Clinicians.\n\n While our core values have stayed the same, BAAD continues to evolve - responding to the needs of our members and advances in dentistry - always staying true to the vision set by our founders.",
    image: "/meetings.webp",
    imageOne: "/sliding-image.webp",
    reverse: true,
  },
];
export const MEMBERSHIP_SAME_SECTION = [
  {
    heading: "Joining the Academy",
    para: "Should you wish to join the Academy, please contact our secretary or forward your contact details to us by email at <a href='mailto:info@baad.org.uk'>info@baad.org.uk.</a>",
    image: "/scimeet2019_57.jpg",
    imageOne: "/sliding-image.webp",
  },
  {
    heading: "Current Academy Members",
    para: "Please feel free to view the <a href='/members' style='font-weight: bold;'>Membership Directory</a>.",
    image: "/meetings.webp",
    imageOne: "/sliding-image.webp",
    reverse: true,
  },
];
export const TESTIMONIALS = [
  {
    name: "Dr Koray Feran BDS MSc FDSRCS",
    para: "“I have been a member of BAAD for 12 years, with 8 of those spent on committee firstly as treasurer and as immediate past president.<br/><br/>BAAD has been an inspiration since my first meeting - the consistent objective of the academy being to promote the highest standards of dental care to restore a patient's appearance and wellbeing to look as natural as possible based on a sound scientific foundation. This never changes and the ethos of BAAD has always been one of sharing knowledge.<br/><br/>The level of presentations is consistently high and of a practical nature and the list of speakers that have attended BAAD over the last 20 years is a who's who of beautiful dentistry.<br/><br/>BAAD has been a family that I have been proud to serve and be associated with and it is gratifying to see the mental and professional stimulation it gives to younger colleagues attending for the first time.<br/><br/>BAAD's scientific meeting and study clubs are a great way to be introduced into the world of quality dentistry and a great group of likeminded colleagues. From the UK and abroad.”",
    ImageSrc: "/Dr-Koray-Feran.jpg",
  },

  {
    name: "Dr Juerg Willi",
    para: "“My initial absolutely coincidental encounter with BAAD has - in hindsight now many years later - turned out to be a true turning point in my outlook on dentistry and the part I should be playing in it. I met an expert group of likeminded people, united in their believe that only a job properly done is a job worth doing.<br/><br/>To be accepted by this group as equal (even though I was not) has been a huge incentive to do likewise and aspire to the same clinical standards. Excellence is not a skill, it is an attitude. Anybody who can live by this bonmot will easily find in BAAD not only encouragment and guidance, but also very good friends (even though they are called BAAD friends).”",
    reverse: true,
    ImageSrc: "/baad-lion.webp",
    lion: true,
  },
  {
    name: "Thomas",
    para: "“High-class aesthetic and implant dentistry in a wonderful venue with great colleagues.<br/><br/>Honestly, I have great memories about the BAAD meeting!<br/><br/>I look forward to seeing you again, hopefully in the near future.”",
    ImageSrc: "/baad-lion.webp",
    lion: true,
  },
];
